name: Android CI

env:

  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # Force all actions to run on Node.js 24

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Old version but runs on Node.js 24
      - name: Build
        run: npm run build
