name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master"]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # Force all actions to run on Node.js 24

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Old version but runs on Node.js 24
      - name: Build
        run: npm run build
        jobs:
  build:
runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
